const moives = [
  "플립",
  "헬프",
  "인셉션",
  "인타임",
  "인턴",
  "킹 오브 티브스",
  "타이타닉(무삭제)",
  "테넷",
  "플로리스",
  "원더휠",
  "웜바디스",
  "위대한 개츠비",
  "어톤먼트",
  "엣지 오브 투모로우",
  "어바웃타임",
  "와일드 라이프",
  "이미테이션 게임",
  "콘스탄틴",
  "프로포즈 데이",
  "실버라이닝 플레이북",
  "아델라인 - 멈춰진 시간",
  "아바타 - 확장판",
  "아임 낫 데어",
  "비커밍 제인",
  "사랑에 대한 모든 것",
  "샬롯의 거미줄",
  "쉬즈 더 맨",
  "시간여행자의 아내",
  "오션스 8",
  "페넬로피",
  "명탐정 피카츄",
  "몬스터콜",
  "미스 페레그린과 이상한 아이들의 집",
  "벤자민버튼의 시간은 거꾸로 간다",
  "매드맥스",
  "블랙 씨",
  "스파이",
  "오만과 편견",
  "의뢰인",
  "파운더",
  "더 웨이 백",
  "도그빌",
  "로맨틱홀리데이",
  "리포맨",
  "마이리틀자이언트",
  "다크나이트",
  "매그니피센트7",
  "보헤미안 랩소디",
  "스턱 인 러브",
  "아쿠아맨",
  "예측은 틀리지 않았다",
  "유스",
  "작은아씨들",
  "투모로우",
  "나는 그녀와 키스했다",
  "내가 널 사랑할 수 없는 10가지 이유",
  "네버랜드를 찾아서",
  "노트북",
  "겟 아웃",
  "고잉인스타일",
  "1. 사자,마녀 그리고 옷장 [The Lion, the Witch and the Wardrobe 2005]",
  "2. 캐스피언 왕자 [Prince Caspian, 2008]",
  "3. 새벽 출정호의 항해 [The Voyage of the Dawn Treader, 2010]",
  "1. 내니 맥피-우리 유모는 마법",
  "2. 내니 맥피-유모와 마법 소동",
  "Men in Black 1, 1997",
  "Men in black 2, 2002",
  "Men in Black 3, 2012",
  "2. 그린델왈드의 범죄 (The Crimes of Grindelwald, 2018)",
  "1. 신비한 동물사전 (Fantastic Beasts and Where to find them, 2016)",
  "2. 망자의 함 [Dead Man's Chest, 2006]",
  "3. 세상의 끝에서 [At World's End, 2007]",
  "4. 낯선 조류 [On Stranger Tides, 2011]",
  "5. 죽은 자는 말이 없다 [Pirates of the Caribbean Dead Men Tell No Tales, 2017]",
  "1. 블랙펄의 저주 [The Curse of the Black Pearl, 2003]",
  "2. 비밀의 방 [The Chamber of Secrests, 2002]",
  "3. 아즈카반의 죄수 [The Prisoner of Azkaban, 2004]",
  "4. 불의 잔 [The Goblet of Fire, 2005]",
  "5. 불사조 기사단 [The order of The Phoenix, 2007]",
  "6. 혼혈왕자 [The half-Blood Prince, 2009]",
  "7. 죽음의 성물 -1 [The Deathly Hallows_Part 1, 2010]",
  "1. 마법사의 돌 [The Philosopher's stone, 2001]",
  "8. 죽음의 성물 -2 [The Deathly Hallows_Part 2, 2011]",
  "가디언즈오브갤럭시 Vol 1",
  "가디언즈오브갤럭시 Vol 2",
  "닥터스트레인지",
  "베놈",
  "1. 스파이더맨",
  "2. 스파이더맨",
  "3. 스파이더맨",
  "4. 어메이징 스파이더맨 1",
  "5. 어메이징 스파이더맨 2",
  "6. 홈커밍 1",
  "7. 파 프롬 홈 2",
  "1. 어벤져스",
  "2. 에이지 오브 울트론",
  "3. 인피니티 워",
  "4. 엔드게임",
  "1. 엔트맨",
  "2. 엔트맨",
  "캡틴마블",
  "1. 천둥의신",
  "2. 다크월드",
  "3. 라그나로크",
  "인크레더블",
  "라따뚜이",
  "라푼젤",
  "모아나",
  "뮬란",
  "업(Up)",
  "보스베이비",
];

const btn = document.querySelector("#btn");
const span = document.querySelector("span");

function moviesClick() {
  const randomMovie = moives[Math.floor(Math.random() * moives.length)];
  span.innerText = randomMovie;
}

btn.addEventListener("click", moviesClick);
